### ISSUE TITLE
Chromium sometimes not using dark mode

### ISSUE THREAD

**Issue by suedunham** [saschaleib/dokuwiki-template-ad-hominem#34]
I'm not sure if I should report this here or elsewhere, but I've noticed some weirdness with the Chromium browser on some—but not all—of the Linux VMs on my Windows host. In that browser, the dark theme is not being used when it should be.

There are no problems with Firefox or Brave on any of the VMs. Chrome in Windows is fine too.

I notice the trouble in my Ubuntu and Manjaro VMs. I have two of each with different front ends, Ubuntu and Xubuntu on the former and Xfce and KDE Plasma on the latter. All are up to date.

However, my two Fedora VMs, the regular Gnome and the KDE Plasma, both give me the dark mode as I expect.

Interestingly, the effect is not total. I am mostly looking at my own template that customizes ad-hominem, though I have verified it in the unmodified template as well. However, in my own, some of my CSS for the dark theme is being implemented. For instance my change in the background color of monospaced text is being used but I don't change the text color, so I get black on black.

That CSS follows. My skills are rudimentary, and if you ask why I did it the way I did, I can't give you any better answer than "That's what seemed to work."

```css
/* Monospaced text */
main code, main code *, main blockquote code, main blockquote code * {
    background-color: __background_site__;
    font-family: "Source Code Pro";
    font-feature-settings: initial;
    font-size: calc(0.95 * __default_font_size__);
    font-weight: 475;
    letter-spacing: -0.04em;
}
body.darkmode main code, body.darkmode main code *,
body.darkmode main blockquote code, body.darkmode main blockquote code * {
    background-color: __background_mono_dark__;
}
```

Other information on the VMs. These are all looking at a wiki hosted locally with IIS on the host computer.

Fedora
Version 110.0.5481.177 (Official Build) Fedora Project (64-bit)
kernel 6.1.14-200.fc37.x86_64

Fedora KDE
Version 110.0.5481.177 (Official Build) Fedora Project (64-bit)
kernel 6.1.14-200.fc37.x86_64

Ubuntu
Version 110.0.5481.177 (Official Build) snap (64-bit)
kernel 5.19.0-35-generic

Xubuntu
Version 110.0.5481.177 (Official Build) snap (64-bit)
kernel 5.19.0-35-generic

Manjaro Xfce
Version 110.0.5481.177 (Official Build) Arch Linux (64-bit)
kernel 6.1.12-1-MANJARO

Manjaro KDE Plasma
Version 110.0.5481.177 (Official Build) Arch Linux (64-bit)
kernel 6.1.12-1-MANJARO
